apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helix-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: helix.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: helix-api
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: helix-web
                port:
                  number: 3000
